Update a4p

diff --git a/a4p b/a4p
--- a/a4p
+++ b/a4p
@@ -9,11 +9,11 @@
 
 ######################i am currently coding from work... windows..... scpipt may be extra unstable untested code, all the functional parts are at the bottom below the functions, you can just edit the variables and select y at the menu
 echo creating variables
-export SDDEV=/dev/sda
+export SDDEV="/dev/sda"
 export SDPARTBOOT=${SDDEV}1
 export SDPARTROOT=${SDDEV}2 #depending on weather one is using usb or nvme, user may need to change this to p1 and p2 respectively.
 
-export SDMOUNT=/mnt/SD
+export SDMOUNT="/mnt/SD"
 
 export DLDIR="~$SUDO_USER/Documents/a4pFiles" #trying this later
 #export DLDIR="$HOME/Documents/a4pFiles" #when ran as sudo chooses root directory, undesirable.  use ~$SUDO_USER here and elsewhere, and notify user when selecting their own paths.#or use sudo -e?   perhaps this: USER_HOME=$(eval echo "~$SUDO_USER")
@@ -23,8 +23,8 @@ export DISTURL="http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.ta
 export RPIKURL="https://fl.us.mirror.archlinuxarm.org/aarch64/core/linux-rpi-6.18.15-1-aarch64.pkg.tar.xz"
 #find raspi kernel link here if updated https://fl.us.mirror.archlinuxarm.org/aarch64/core/
 
-export LOCALFILES=n
-#export LOCALFILES=n
+export LOCALFILES="n"
+#export LOCALFILES="n"
 
 
 a4pDev() {
@@ -197,8 +197,8 @@ fi
 echo "$SDDEV will be mounted at $SDMOUNT."
 
 read -p "Does everything look correct? y to execute program with given parameters, any other key for menu." choice
-if [[ $choice == "y" ]]; then
-
+if [[ "$choice" == "y" ]]; then
+	:
 else
 	ap4menu
 fi
@@ -208,13 +208,13 @@ fi
 ############################functional part pasted in
 
 
-if [[ $LOCALFILES == "n" ]]; then
+if [[ "$LOCALFILES" == "n" ]]; then
 	echo  make directory for arch image DL
-	mkdir -p $DLDIR
-	cd $DLDIR
+	mkdir -p "$DLDIR"
+	cd $DLDIR || echo "cd failed, returning to menu."; a4pMenu
 	curl -JLO "$DISTURL"
 else
-	cd "$DLDIR"  # shellcheck recommends: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
+	cd "$DLDIR" || echo "cd failed, returning to menu."; a4pMenu
 fi
 
 
@@ -226,36 +226,36 @@ sudo sfdisk --quiet --wipe always "$SDDEV" << EOF
 EOF
 
 	echo "create filesystem"
-sudo mkfs.vfat -F 32 $SDPARTBOOT
-sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -F $SDPARTROOT
+sudo mkfs.vfat -F 32 "$SDPARTBOOT"
+sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -F "$SDPARTROOT"
 
 	echo "write image to disk, this will take a while."
-mkdir -p $SDMOUNT
-mount $SDPARTROOT $SDMOUNT
+mkdir -p "$SDMOUNT"
+mount "$SDPARTROOT" "$SDMOUNT"
 mkdir -p ${SDMOUNT}/boot
-mount $SDPARTBOOT ${SDMOUNT}/boot
+mount "$SDPARTBOOT" ${SDMOUNT}/boot
 
-bsdtar -xvpf ${DLDIR}/${DISTURL##*/} -C $SDMOUNT
+bsdtar -xvpf ${DLDIR}/${DISTURL##*/} -C "$SDMOUNT"
 #bsdtar -xvpf ${DLDIR}/ArchLinuxARM-rpi-aarch64-latest.tar.gz -C $SDMOUNT
 
 
 
   echo remove arch bootloader
-rm -rf ${SDMOUNT}/boot/*   #shellcheck recommends: Use "${var:?}" to ensure this never expands to /boot/* .
+rm -rf ${SDMOUNT}/boot/* || echo "failed to remove arch bootloader, returning to menu"; a4pMenu   #shellcheck recommends Use "${var:?}" to ensure this never expands to /boot/* .
 
 
 
   echo "install raspi kernel"
-#if [[ $LOCALFILES == n ]]; then    #TEST THIS
+if [[ "$LOCALFILES" == n ]]; then    #TEST THIS
 	mkdir -p ${DLDIR}/linux-rpi
 	pushd ${DLDIR}/linux-rpi   #shecllcheck recommends: Use 'pushd ... || exit' or 'pushd ... || return' in case pushd fails.
 	#####################################problems
-	curl -JLO $RPIKURL
-#else
-	pushd ${DLDIR}/linux-rpi  #shellchekc reccomends: Use 'pushd ... || exit' or 'pushd ... || return' in case pushd fails.
-#fi
+	curl -JLO "$RPIKURL"
+else
+	pushd ${DLDIR}/linux-rpi || echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu  #shellchekc reccomends: Use 'pushd ... || exit' or 'pushd ... || return' in case pushd fails.
+fi
 
-cd ${DLDIR}/linux-rpi
+cd ${DLDIR}/linux-rpi 
 
 tar xf ${DLDIR}/linux-rpi/${RPIKURL##*/}
 #tar xf ${DLDIR}/linux-rpi/linux-rpi-6.12.58-1-aarch64.pkg.tar.xz
@@ -294,13 +294,13 @@ echo "Syncing, takes a while patience"
 sync && umount -R $SDMOUNT
 echo "COMPLETED. Eject and boot pi"
 
-if [[ $DLDIR == /tmp* ]]; then
-	rm -r "$DLDIR"
+if [[ "$DLDIR" == /tmp* ]]; then
+	rm -r "$DLDIR" || echo "failed to delete OS install files at $DLDIR"; exit
 	echo "debug for del tmp"
 fi
 
 echo "Clean up after ourself, exiting."
-rm -r $SDMOUNT
+rm -r $SDMOUNT || echo "faailed to delete mount folder at $SDMOUNT"; exit
 exit
 
 
